import React from 'react'
import { Providers } from './providers';
import { Cairo, Raleway } from "next/font/google";
import 'swiper/css/bundle';
import "./globals.css";
import { Metadata } from 'next';
import { updateLocale } from '@/app/api/api_services';

const raleway = Raleway({
  variable: '--font-raleway-sans',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', "900"],
  subsets: ['latin']
})
const cairo = Cairo({
  variable: '--font-raleway-sans',
  weight: ['1000', '200', '300', '400', '500', '600', '700', '800', "900"],
  subsets: ['latin']
})
export const metadata: Metadata = {
  title: "Souq Al-Sham",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children, params
}: Readonly<{
  children: React.ReactNode,
  params: Promise<{ locale: string, }>
}>) {

  const { locale } = await params
  updateLocale(locale)
  return (
    <html lang={locale} dir={locale === 'ar' ? 'rtl' : 'ltr'} data-theme={''}>
      <body
        className={`${locale === 'ar' ? cairo.className : raleway.className} antialiased`}
      >
        <Providers locale={locale}>
          {children}
        </Providers>
      </body>
    </html>
  )
}
